### ISSUE TITLE
Как взять свободную задачу

### ISSUE THREAD

**Issue by kulakovt** [EduWebDotNet/methodology#17]
Необходимо написать статью в wiki о том как можно взять на себя свободную задачу для работы.

Статья должна отвечать на вопросы:

- где искать задачи
- как отличать задачу, которую можно взять сейчас в работу от той которую (по каким-то причинам) брать не следует
- как закрепить выбранную задачу за собой
- куда задавать вопросы по реализации
- куда сообщать промежуточный статус о прогрессе
- как определить что задача реализована полностью (критерии приёмки)
- как послать задачу на проверку
- когда результат работы попадёт в master

**Comment by nealcrafter** [comment]
Толя, посмотри драфт описания [Task rules](https://github.com/EduWebDotNet/methodology/wiki/Task-rules)
Из основного нужно понять как будем разделять задачи на те которые можно брать в работу, и те которые пока не берем (ожидает другую задачу. пока нет решения, неприоритетная), можно использовать Labels, Milestone, или попробовать статусы в проектах. У тебя какое было видение в этой части?

**Comment by kulakovt** [comment]
> те которые можно брать в работу, и те которые пока не берем

У меня нет никаких предпочтений. Если у кого-то есть пожелания, предлагайте.

Думаю на первое время можно придерживаться правила:

- если у задачи ещё нет исполнителя, то её можно взять в работу

Если потом нужно будет что-то более сложное, накрутим.
