### ISSUE TITLE
Написать текстовую часть к теме №1

### ISSUE THREAD

**Issue by max-arshinov** [EduWebDotNet/methodology#3]
Зависит от:

-  #10 

Тема 1 https://github.com/max-arshinov/web-dev-csharp-react/tree/main/hands-on/2/1/Homework1. Содержит только ссылки. Сопроводительный текст (конспект лекции), объясняющий связь теории с практическим заданием помог бы лучше усвоить материал. Такой текст нужно написать.

Можно взять одну тему

**Comment by max-arshinov** [comment]
Пример (не самый клёвый) такого текста

## Введение
Перед тем как начать работу над основным [практическим заданием](...) Вам нужно научиться тестировать
свой код и создавать web-приложения.

1. [Разминка](Tasks/intro.md)
2. [Тестирование](Tasks/testing.md)
3. [Знакомство с ASP.NET](Tasks/asp-net.md)

## Основная часть

До конца курса вы будете работать с одним [практическим заданием](...). 
Задание слишком объемно, чтобы выполнить его за один раз, поэтому оно разбито на небольшие части.
Выполняйте задания по списку и в конце концов, Вы справитесь. Дорогу осилит идущий.

4. [REST API](Tasks/rest.md)

**Идея**
Для экномии времени можно попробовать скармливать тексты Chat GPT, чтобы он писал выжимку. 4 версия часто хорошо справляется с такими задачами. Результат требует человеческой редактуры, но может сэкномить время.

**Comment by MorozovKirill310** [comment]
@max-arshinov @kulakovt 

Посидел, покрутил.
В результате построения текста вокруг заданного набора ссылок у меня выходит либо словоблудие вокруг да около, либо краткий пересказ изложенного в оригинальных материалах.

Лучшее, из того, что у меня получилось - это те же ссылки и несколько предваряющих вводных предложений:


Не знаем кто ты, человек читающий этот текст, но уверены, что у тебя совсем немного времени и с каждым днем его не становится больше.
Чтобы помочь с организацией твоих задач и отыскать в твоем и без того плотном графике время на изучение нашего курса,
в качестве вступления предлагаем ознакомиться с материалами об управлении временем и приоритетами:
- [Что такое матрица Эйзенхауэра](https://timeweb.com/ru/community/articles/chto-takoe-matrica-eyzenhauera) - лаконичная и емкая статья Виктора Бухтеева, описывающая методику приоритезации задач;
- [Джедайская техника 2.0](https://www.youtube.com/watch?v=jt3_sq8LQYM) - объемная видео лекция от Максима Дорофеева, затрагивающая различные аспекты продуктивности ([вместо содержания](https://www.mindmeister.com/app/map/784644595?t=Yxc972Ienc)).

В профессии, как и в жизни, есть задачи и есть средства и инструменты, помогающие в их решении.
Инструменты бывают разные: одни лежат в шкафу, ожидая той самой уникальной задачи, для решения которой без них не обойтись, другие постоянно находятся на столе профессионала, те без которых не обходится решение ни одной повседневной задачи.
Современную разработку сложно представить без постоянного использования системы контроля версий и различных методик и средств тестирования кода. 
Поэтому в качестве обязательных начальных материалов предлагаем изучить:
- [Ежедневная работа с Git](https://habr.com/ru/articles/174467/) - статья Евгения Артюхова познакомит с некоторыми особенностями устройства и сценариями использования наиболее популярной на сегодняшний день системы контроля версий Git;
- [Юнит-тестирование для чайников](https://habr.com/ru/articles/169381/) - статья Максима Аршинова отвечает на вопросы Когда? Зачем? и Как? нужно использовать unit-тесты.


Не знаю на сколько это близко к тому, что требовалось.

**Comment by kulakovt** [comment]
> Не знаем кто ты, человек читающий этот текст

Нужно выбрать жанр повествования, способы обращения и манеру изложения. Скорее всего, за основу можно взять IT-литературу. Там никогда не обращаются к читателю напрямую. Это сильно упрощает жизнь ибо не надо отвечать на множество вопросов о читателе (он или она, ты или вы, начинающий или опытный и т.д.). Т.е. рассказывать надо о материале, а не общаться с индивидуумом.

Например

> Современные знания об информационных системах объёмны и многогранны. Даже если выбрать узкоспециализированное направление, данных для освоения настолько много, что без систематического подхода к изучению справиться с ними будет сложно.

Возможно будет легче описать каждую ссылку если попробовать в одном абзаце ответить на несколько базовых вопросов: какую проблему решает материал по ссылке, что будет если её не решать, кому он будет полезен, чем данная ссылка отличается от других подобных, чему научится ученик после освоения ссылки.

Но я совсем не писатель. Тут нужно ревью от @max-arshinov .

**Comment by MorozovKirill310** [comment]
@kulakovt Спасибо, попробовал подумать в предложенном тобой ключе:

> ответить на несколько базовых вопросов.

При таком подходе у меня получается некая рецензия на представленный по ссылке материал.

Это точно то, чего мы хотим?

Мне видится необходимым предложить некий связующий текст (клей) к набору отобранных материалов.

**Comment by max-arshinov** [comment]
Я представлял немного иначе, более "книжно". Давай попробуй написать 1-2 примера и сравним

**Comment by max-arshinov** [comment]
@max-arshinov тут должно быть “давай я попробую”, отредактировал комментарий, бот не оповещает об этом

**Comment by MorozovKirill310** [comment]
@max-arshinov Давай попробуем, конечно. Но я не понимаю смысл описывать "книжно" и прилагать ссылки на материалы, представленные в произвольной форме. Тогда уж и источники нужны более фундаментальные. ИМХО

**Comment by kulakovt** [comment]
Собрал материал первого модуля в [ori структуру](https://github.com/EduWebDotNet/methodology/wiki/Ori) и влил в master
