### ISSUE TITLE
Придумать систему "тегов/путей", добавить "теги"

### ISSUE THREAD

**Issue by max-arshinov** [EduWebDotNet/methodology#9]
Структура курса - https://docs.google.com/spreadsheets/d/1TCYWmFmCPdu56p1KPKxvKCdz2Sbr6jpzoCDfwLWsLBk/edit#gid=0

На обсуждении методологов решили, что была бы полезна система тегов, потому что не все задания одинаково интересны всем преподавателям. Например, кто-то хочет сначала дать unit-тестирование и основы ASP.NET и взять на стажировку, а потом уже давать "основы платформы".

Вдохновиться
- path: https://www.pluralsight.com/paths/microsoft-azure-ai-conference-2019
- applied skills: https://learn.microsoft.com/en-us/credentials/browse/?credential_types=applied%20skills&products=azure

Слайд, объясняющий почему в курсе "матан" (канкаренси, IL и т.д.)

![Image](https://github.com/EduWebDotNet/Methodology/assets/820550/6a2117b3-f4c8-4f58-9671-d9b44fb5ec7c)

**Comment by max-arshinov** [comment]
Точно должен быть путь "микросерисы/распределенные системы". Это по сути весь третий семестр. Уровни сложности:
- Простой - Aspire
- Средний - Docker Compose
- Сложный -K8S

Нужны ли пути "мобильная разработка", "кросс-платформа" (Авалония и иже с ним)?

**Comment by MorozovKirill310** [comment]
Оставлю в качестве идеи:
Рассматривать не отдельные пути, а единый взвешенный, ориентированный граф: вершины - темы, ребра - последовательность изучения. И возможность рассматривать граф в разных «измерениях», например, сложность (глубина) изучения.

**Comment by MorozovKirill310** [comment]
Еще немного мыслей в эту сторону:

Изначально, познакомившись с формой изложения теоретического материала в разработанном Максимом курсе (набор ссылок), я ошибочно недооценил ее ценности и роли методолог, как «производителя» этой формы. Показалось, что на месте ссылок должен быть некий агрегированный материал, а ответственность методолога - агрегация.

Теперь пересмотрел свое понимание. Важно не то, что это ссылки, о то на материалы какого «качества» они ведут. Из этого следует и ответственность методолога - фильтрация и категоризация общедоступных материалов.

В этом свете модель графа, описанная в комментарии выше, выглядит еще более интересной, ИМХО. Вершина - набор актуальных на текущий момент, отобранных «экспертным» мнением материалов по заданной теме.

**Comment by MorozovKirill310** [comment]
Одним из «измерений» графа можно сделать тип материала (кому-то больше подходят книги, другим статьи, третьим видео или подкасты). Также одним из неочевидных, на первый взгляд, источников (типов) могут быть «обсуждения»: комментарии, чаты. Поиск и фильтрация такого рода источников, в разы сложнее, но тем ценнее их наличие в курсе, ИМХО.

**Comment by kulakovt** [comment]
Одним документом обойтись не получилось. Поэтому я завёл страничку с [Словарём](https://github.com/EduWebDotNet/methodology/wiki/Dictionary) нашего домена. Описал [структуру курса](https://github.com/EduWebDotNet/methodology/wiki/Course-structure). Затронул разметку метаданных с помощью различных [измерений](https://github.com/EduWebDotNet/methodology/wiki/Dimensions) и [dimoji](https://github.com/EduWebDotNet/methodology/wiki/Dimoji).

Нужны ваши комментарии. Особенно на счёт понятности и целесообразности написанного. Обсуждения наверное лучше вести в этой задаче, чтобы не терялись комментарии.
